/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'

const TrendingLazyRouteImport = createFileRoute('/trending')()
const SettingsLazyRouteImport = createFileRoute('/settings')()
const SearchLazyRouteImport = createFileRoute('/search')()
const ReadingHistoryLazyRouteImport = createFileRoute('/reading-history')()
const ProfileLazyRouteImport = createFileRoute('/profile')()
const LatestUpdatesLazyRouteImport = createFileRoute('/latest-updates')()
const FavoritesLazyRouteImport = createFileRoute('/favorites')()
const AuthLazyRouteImport = createFileRoute('/auth')()
const R404LazyRouteImport = createFileRoute('/404')()
const IndexLazyRouteImport = createFileRoute('/')()
const MangaMangaIdLazyRouteImport = createFileRoute('/manga/$mangaId')()
const ChapterChapterIdLazyRouteImport = createFileRoute('/chapter/$chapterId')()
const AuthorAuthorIdLazyRouteImport = createFileRoute('/author/$authorId')()
const AdminUsersLazyRouteImport = createFileRoute('/admin/users')()
const AdminMessagesLazyRouteImport = createFileRoute('/admin/messages')()
const AdminFeedbackLazyRouteImport = createFileRoute('/admin/feedback')()
const AdminDashboardLazyRouteImport = createFileRoute('/admin/dashboard')()
const GroupMangadexGroupIdLazyRouteImport = createFileRoute(
  '/group/mangadex/$groupId',
)()
const GroupLocalGroupIdLazyRouteImport = createFileRoute(
  '/group/local/$groupId',
)()

const TrendingLazyRoute = TrendingLazyRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/trending.lazy').then((d) => d.Route))
const SettingsLazyRoute = SettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const SearchLazyRoute = SearchLazyRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/search.lazy').then((d) => d.Route))
const ReadingHistoryLazyRoute = ReadingHistoryLazyRouteImport.update({
  id: '/reading-history',
  path: '/reading-history',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/reading-history.lazy').then((d) => d.Route),
)
const ProfileLazyRoute = ProfileLazyRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))
const LatestUpdatesLazyRoute = LatestUpdatesLazyRouteImport.update({
  id: '/latest-updates',
  path: '/latest-updates',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/latest-updates.lazy').then((d) => d.Route),
)
const FavoritesLazyRoute = FavoritesLazyRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/favorites.lazy').then((d) => d.Route))
const AuthLazyRoute = AuthLazyRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth.lazy').then((d) => d.Route))
const R404LazyRoute = R404LazyRouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/404.lazy').then((d) => d.Route))
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const MangaMangaIdLazyRoute = MangaMangaIdLazyRouteImport.update({
  id: '/manga/$mangaId',
  path: '/manga/$mangaId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/manga.$mangaId.lazy').then((d) => d.Route),
)
const ChapterChapterIdLazyRoute = ChapterChapterIdLazyRouteImport.update({
  id: '/chapter/$chapterId',
  path: '/chapter/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/chapter.$chapterId.lazy').then((d) => d.Route),
)
const AuthorAuthorIdLazyRoute = AuthorAuthorIdLazyRouteImport.update({
  id: '/author/$authorId',
  path: '/author/$authorId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/author.$authorId.lazy').then((d) => d.Route),
)
const AdminUsersLazyRoute = AdminUsersLazyRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin.users.lazy').then((d) => d.Route))
const AdminMessagesLazyRoute = AdminMessagesLazyRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.messages.lazy').then((d) => d.Route),
)
const AdminFeedbackLazyRoute = AdminFeedbackLazyRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.feedback.lazy').then((d) => d.Route),
)
const AdminDashboardLazyRoute = AdminDashboardLazyRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.dashboard.lazy').then((d) => d.Route),
)
const GroupMangadexGroupIdLazyRoute =
  GroupMangadexGroupIdLazyRouteImport.update({
    id: '/group/mangadex/$groupId',
    path: '/group/mangadex/$groupId',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/group.mangadex.$groupId.lazy').then((d) => d.Route),
  )
const GroupLocalGroupIdLazyRoute = GroupLocalGroupIdLazyRouteImport.update({
  id: '/group/local/$groupId',
  path: '/group/local/$groupId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/group.local.$groupId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminRouteWithChildren
  '/404': typeof R404LazyRoute
  '/auth': typeof AuthLazyRoute
  '/favorites': typeof FavoritesLazyRoute
  '/latest-updates': typeof LatestUpdatesLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/reading-history': typeof ReadingHistoryLazyRoute
  '/search': typeof SearchLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/trending': typeof TrendingLazyRoute
  '/admin/dashboard': typeof AdminDashboardLazyRoute
  '/admin/feedback': typeof AdminFeedbackLazyRoute
  '/admin/messages': typeof AdminMessagesLazyRoute
  '/admin/users': typeof AdminUsersLazyRoute
  '/author/$authorId': typeof AuthorAuthorIdLazyRoute
  '/chapter/$chapterId': typeof ChapterChapterIdLazyRoute
  '/manga/$mangaId': typeof MangaMangaIdLazyRoute
  '/group/local/$groupId': typeof GroupLocalGroupIdLazyRoute
  '/group/mangadex/$groupId': typeof GroupMangadexGroupIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminRouteWithChildren
  '/404': typeof R404LazyRoute
  '/auth': typeof AuthLazyRoute
  '/favorites': typeof FavoritesLazyRoute
  '/latest-updates': typeof LatestUpdatesLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/reading-history': typeof ReadingHistoryLazyRoute
  '/search': typeof SearchLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/trending': typeof TrendingLazyRoute
  '/admin/dashboard': typeof AdminDashboardLazyRoute
  '/admin/feedback': typeof AdminFeedbackLazyRoute
  '/admin/messages': typeof AdminMessagesLazyRoute
  '/admin/users': typeof AdminUsersLazyRoute
  '/author/$authorId': typeof AuthorAuthorIdLazyRoute
  '/chapter/$chapterId': typeof ChapterChapterIdLazyRoute
  '/manga/$mangaId': typeof MangaMangaIdLazyRoute
  '/group/local/$groupId': typeof GroupLocalGroupIdLazyRoute
  '/group/mangadex/$groupId': typeof GroupMangadexGroupIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminRouteWithChildren
  '/404': typeof R404LazyRoute
  '/auth': typeof AuthLazyRoute
  '/favorites': typeof FavoritesLazyRoute
  '/latest-updates': typeof LatestUpdatesLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/reading-history': typeof ReadingHistoryLazyRoute
  '/search': typeof SearchLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/trending': typeof TrendingLazyRoute
  '/admin/dashboard': typeof AdminDashboardLazyRoute
  '/admin/feedback': typeof AdminFeedbackLazyRoute
  '/admin/messages': typeof AdminMessagesLazyRoute
  '/admin/users': typeof AdminUsersLazyRoute
  '/author/$authorId': typeof AuthorAuthorIdLazyRoute
  '/chapter/$chapterId': typeof ChapterChapterIdLazyRoute
  '/manga/$mangaId': typeof MangaMangaIdLazyRoute
  '/group/local/$groupId': typeof GroupLocalGroupIdLazyRoute
  '/group/mangadex/$groupId': typeof GroupMangadexGroupIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/404'
    | '/auth'
    | '/favorites'
    | '/latest-updates'
    | '/profile'
    | '/reading-history'
    | '/search'
    | '/settings'
    | '/trending'
    | '/admin/dashboard'
    | '/admin/feedback'
    | '/admin/messages'
    | '/admin/users'
    | '/author/$authorId'
    | '/chapter/$chapterId'
    | '/manga/$mangaId'
    | '/group/local/$groupId'
    | '/group/mangadex/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/404'
    | '/auth'
    | '/favorites'
    | '/latest-updates'
    | '/profile'
    | '/reading-history'
    | '/search'
    | '/settings'
    | '/trending'
    | '/admin/dashboard'
    | '/admin/feedback'
    | '/admin/messages'
    | '/admin/users'
    | '/author/$authorId'
    | '/chapter/$chapterId'
    | '/manga/$mangaId'
    | '/group/local/$groupId'
    | '/group/mangadex/$groupId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/404'
    | '/auth'
    | '/favorites'
    | '/latest-updates'
    | '/profile'
    | '/reading-history'
    | '/search'
    | '/settings'
    | '/trending'
    | '/admin/dashboard'
    | '/admin/feedback'
    | '/admin/messages'
    | '/admin/users'
    | '/author/$authorId'
    | '/chapter/$chapterId'
    | '/manga/$mangaId'
    | '/group/local/$groupId'
    | '/group/mangadex/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AdminRoute: typeof AdminRouteWithChildren
  R404LazyRoute: typeof R404LazyRoute
  AuthLazyRoute: typeof AuthLazyRoute
  FavoritesLazyRoute: typeof FavoritesLazyRoute
  LatestUpdatesLazyRoute: typeof LatestUpdatesLazyRoute
  ProfileLazyRoute: typeof ProfileLazyRoute
  ReadingHistoryLazyRoute: typeof ReadingHistoryLazyRoute
  SearchLazyRoute: typeof SearchLazyRoute
  SettingsLazyRoute: typeof SettingsLazyRoute
  TrendingLazyRoute: typeof TrendingLazyRoute
  AuthorAuthorIdLazyRoute: typeof AuthorAuthorIdLazyRoute
  ChapterChapterIdLazyRoute: typeof ChapterChapterIdLazyRoute
  MangaMangaIdLazyRoute: typeof MangaMangaIdLazyRoute
  GroupLocalGroupIdLazyRoute: typeof GroupLocalGroupIdLazyRoute
  GroupMangadexGroupIdLazyRoute: typeof GroupMangadexGroupIdLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading-history': {
      id: '/reading-history'
      path: '/reading-history'
      fullPath: '/reading-history'
      preLoaderRoute: typeof ReadingHistoryLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest-updates': {
      id: '/latest-updates'
      path: '/latest-updates'
      fullPath: '/latest-updates'
      preLoaderRoute: typeof LatestUpdatesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga/$mangaId': {
      id: '/manga/$mangaId'
      path: '/manga/$mangaId'
      fullPath: '/manga/$mangaId'
      preLoaderRoute: typeof MangaMangaIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapter/$chapterId': {
      id: '/chapter/$chapterId'
      path: '/chapter/$chapterId'
      fullPath: '/chapter/$chapterId'
      preLoaderRoute: typeof ChapterChapterIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/$authorId': {
      id: '/author/$authorId'
      path: '/author/$authorId'
      fullPath: '/author/$authorId'
      preLoaderRoute: typeof AuthorAuthorIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/group/mangadex/$groupId': {
      id: '/group/mangadex/$groupId'
      path: '/group/mangadex/$groupId'
      fullPath: '/group/mangadex/$groupId'
      preLoaderRoute: typeof GroupMangadexGroupIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/local/$groupId': {
      id: '/group/local/$groupId'
      path: '/group/local/$groupId'
      fullPath: '/group/local/$groupId'
      preLoaderRoute: typeof GroupLocalGroupIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardLazyRoute: typeof AdminDashboardLazyRoute
  AdminFeedbackLazyRoute: typeof AdminFeedbackLazyRoute
  AdminMessagesLazyRoute: typeof AdminMessagesLazyRoute
  AdminUsersLazyRoute: typeof AdminUsersLazyRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardLazyRoute: AdminDashboardLazyRoute,
  AdminFeedbackLazyRoute: AdminFeedbackLazyRoute,
  AdminMessagesLazyRoute: AdminMessagesLazyRoute,
  AdminUsersLazyRoute: AdminUsersLazyRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AdminRoute: AdminRouteWithChildren,
  R404LazyRoute: R404LazyRoute,
  AuthLazyRoute: AuthLazyRoute,
  FavoritesLazyRoute: FavoritesLazyRoute,
  LatestUpdatesLazyRoute: LatestUpdatesLazyRoute,
  ProfileLazyRoute: ProfileLazyRoute,
  ReadingHistoryLazyRoute: ReadingHistoryLazyRoute,
  SearchLazyRoute: SearchLazyRoute,
  SettingsLazyRoute: SettingsLazyRoute,
  TrendingLazyRoute: TrendingLazyRoute,
  AuthorAuthorIdLazyRoute: AuthorAuthorIdLazyRoute,
  ChapterChapterIdLazyRoute: ChapterChapterIdLazyRoute,
  MangaMangaIdLazyRoute: MangaMangaIdLazyRoute,
  GroupLocalGroupIdLazyRoute: GroupLocalGroupIdLazyRoute,
  GroupMangadexGroupIdLazyRoute: GroupMangadexGroupIdLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
